npm i browserify
npm i browserify-package-json
npm i colors
npm i crawler
npm i crypto
npm i express
npm i express-juicer
npm i html-entities
npm i http-proxy
npm i magnet-uri
npm i npm-run-path
npm i qrcode
npm i qrcode-reader
npm i spdx-expression-parse
npm i uglify-js
npm i urlencode
npm i validate-npm-package-license
